DROP DATABASE IF EXISTS `OLYMPIA`;
create DATABASE OLYMPIA;
use OLYMPIA;

DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `BRANCH`;
DROP TABLE IF EXISTS `TRAINER`;
DROP TABLE IF EXISTS `NON_TRAINER_STAFF`;
DROP TABLE IF EXISTS `FINANCE`;
DROP TABLE IF EXISTS `EQUIPMENTS`;
DROP TABLE IF EXISTS `ALUMNI`;

CREATE TABLE `MEMBER`(
	MEMBER_ID INT NOT NULL,
    BRANCH_CODE INT NOT NULL,
    CITY_CODE INT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
	EMAIL VARCHAR(50),
	ADDRESS VARCHAR(50),
	GENDER VARCHAR(10) NOT NULL,
	DOB VARCHAR(20),
	AGE_GROUP VARCHAR(30) NOT NULL,
    HEIGHT INT NOT NULL,
    WEIGHT INT NOT NULL,
	PRIMARY KEY(`MEMBER_ID`)
);

CREATE TABLE `BRANCH`(
    CITY_CODE INT NOT NULL,
    BRANCH_PLACE VARCHAR(30) NOT NULL,
    BRANCH_CODE INT NOT NULL,
    BRANCH_HEAD VARCHAR(30) NOT NULL,
    PRIMARY KEY(`BRANCH_CODE` , `CITY_CODE`)
    -- PRIMARY KEY(`CITY_CODE`)
);

CREATE TABLE `TRAINER`(
	TRAINER_ID INT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
	ADDRESS VARCHAR(50),
    BRANCH_CODE INT NOT NULL,
	CONTACT_NUMBER BIGINT NOT NULL,
    AGE_GROUP VARCHAR(39) NOT NULL,
    WORK_EXPERIENCE INT,
    PRIMARY KEY(`TRAINER_ID`)
);

CREATE TABLE `NON_TRAINER_STAFF`(
	NON_TRAINER_STAFF_ID INT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
    EMAIL VARCHAR(50),
    WORK VARCHAR(30) NOT NULL,
    SALARY INT NOT NULL,
    BRANCH_CODE INT NOT NULL,
	PRIMARY KEY(`NON_TRAINER_STAFF_ID`)
);

CREATE TABLE `FINANCE`(
	BRANCH_ID INT,
    EXPENDITURE INT NOT NULL,
    MONTH INT NOT NULL,
    INCOME INT NOT NULL,
    PROFIT INT NOT NULL,
    FOREIGN KEY(`BRANCH_ID`) REFERENCES `BRANCH`(`BRANCH_CODE`)
);
CREATE TABLE `EQUIPMENTS`(
	MODEL VARCHAR(30) NOT NULL,
    BRANCH_CODE INT NOT NULL,
    TAG_ID INT NOT NULL,
    HALAT VARCHAR(30) NOT NULL,
    NUMBER_OF_PARTS INT NOT NULL,
    BODY_PART VARCHAR(30) NOT NULL,
    PRIMARY KEY(`TAG_ID`)
);

CREATE TABLE `ALUMNI`(
    MEMBER_ID INT,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
    COMPETITION_NAME VARCHAR(30) NOT NULL,
    COMPETITION_LEVEL VARCHAR(30),
    COMPETITION_RANK VARCHAR(30),
    YEAR INT NOT NULL,
    FOREIGN KEY(`MEMBER_ID`) REFERENCES `MEMBER`(`MEMBER_ID`)
);
 
CREATE TABLE `MEMBER_TRAINED_IN_BRANCH`(
    BRANCH_CODE INT NOT NULL,
	TRAINER_ID INT NOT NULL,
	MEMBER_ID INT NOT NULL,
	FOREIGN KEY(`BRANCH_CODE`) REFERENCES `BRANCH`(`BRANCH_CODE`),
	FOREIGN KEY(`TRAINER_ID`) REFERENCES `TRAINER`(`TRAINER_ID`),
	FOREIGN KEY(`MEMBER_ID`) REFERENCES `MEMBER`(`MEMBER_ID`)
);
-- training
DROP TABLE IF EXISTS `TRAINING`;
CREATE TABLE `TRAINING`(
    TRAINER_ID INT NOT NULL,
    BRANCH_CODE INT NOT NULL,
    CITY_CODE INT NOT NULL,
    FOREIGN KEY(`TRAINER_ID`) REFERENCES `TRAINER`(`TRAINER_ID`),
    FOREIGN KEY(`BRANCH_CODE`, `CITY_CODE`) REFERENCES `BRANCH`(`BRANCH_CODE`, `CITY_CODE`)
);

DROP TABLE IF EXISTS `PAYING`;
CREATE TABLE `PAYING`(
	BRANCH_CODE INT NOT NULL,
    CITY_CODE INT NOT NULL,
    NON_TRAINER_STAFF_ID INT NOT NULL,
    FOREIGN KEY(`BRANCH_CODE`, `CITY_CODE`) REFERENCES `BRANCH`(`BRANCH_CODE`, `CITY_CODE`),
    FOREIGN KEY(`NON_TRAINER_STAFF_ID`) REFERENCES `NON_TRAINER_STAFF`(`NON_TRAINER_STAFF_ID`)
);
DROP TABLE IF EXISTS `EARNING`;
CREATE TABLE `EARNING`(
    BRANCH_CODE INT NOT NULL,
    CITY_CODE INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    FOREIGN KEY(`BRANCH_CODE`, `CITY_CODE`) REFERENCES `BRANCH`(`BRANCH_CODE`, `CITY_CODE`),
    FOREIGN KEY(`BRANCH_ID`) REFERENCES `FINANCE`(`BRANCH_ID`)
);



INSERT INTO `MEMBER` VALUES (2021001, 2001 , 1 , 'VAIBHAV', 'AGARWAL','vaibh2@gmail.com','Pune','M', '01/01/2000', 'A', '182', '87');
INSERT INTO `MEMBER` VALUES (2021002, 2002 , 2 ,'ABHISHEK', 'SHARMA', 'abhi@gmail.com','Mumbai','M', '01/01/1996', 'B', '175', '74');
INSERT INTO `MEMBER` VALUES (2021003,2003 , 3,'SIDDHARTH', 'SHARMA', 'sid@gmail.com','Hyderabad','M', '15/12/1996', 'B', '172', '70');
INSERT INTO `MEMBER` VALUES (2021004, 2004 , 4 ,'SARTHAK', 'AGGARWAL','sart.tatta@gmail.com','Delhi','M', '22/11/2002', 'A', '170', '90');
INSERT INTO `MEMBER` VALUES (2021005,2005 , 5 ,'POOJA', 'DESUR', 'pooja@gmail.com','Kolkata','F', '01/01/1999', 'B', '165', '65');
INSERT INTO `MEMBER` VALUES (2021006, 2006 , 5,'HARSHITA', 'UPADHYAY', 'harshita@outlook.com','Pune','F', '23/12/1992', 'C', '170', '70');


INSERT INTO `BRANCH` VALUES (1, 'Mumbai', 2001 ,'Siddharth');
INSERT INTO `BRANCH` VALUES (2, 'Pune', 2002 ,'Gargi');
INSERT INTO `BRANCH` VALUES (3, 'Delhi', 2003 ,'Nikhil');
INSERT INTO `BRANCH` VALUES (4, 'Kolkata', 2004 ,'Tirth');
INSERT INTO `BRANCH` VALUES (5, 'Hyderabad', 2005 ,'Mitul');
INSERT INTO `BRANCH` VALUES (5, 'Hyderabad', 2006 ,'Tarun');



INSERT INTO `TRAINER` VALUES (1, 'Siddharth', 'Agarwal', 'Pune', 2002, '9876543210', 'A', '5');
INSERT INTO `TRAINER` VALUES (2, 'Gargi', 'Yadav', 'Mumbai', 2001, '9876543210', 'B', '3');
INSERT INTO `TRAINER` VALUES (3, 'Nikhil', 'Sharma', 'Delhi', 2003, '9876543210', 'B', '2');
INSERT INTO `TRAINER` VALUES (4, 'Rahul', 'Sharma', 'Kolkata', 2004, '9876543210', 'C', '1');
INSERT INTO `TRAINER` VALUES (5, 'Mayank', 'Kabra', 'Hyderabad', 2005, '9876543210', 'C', '1');
INSERT INTO `TRAINER` VALUES (6, 'Hardik', 'Gupta', 'Hyderabad', 2006, '9876543210', 'C', '1');
INSERT INTO `TRAINER` VALUES (7, 'Siddharth', 'Agarwal', 'Pune', 2002, '9876543210', 'A', '5');



INSERT INTO `NON_TRAINER_STAFF` VALUES (1, 'Om' , 'Pk' , 'kaop.@gmail.com' , 'Jhadu' , 5000 , 2001 );

INSERT INTO `NON_TRAINER_STAFF` VALUES (2, 'Chandan' , 'Bharadwaj' , 'chandan@gmail.com' , 'Poucha' , 7000 , 2002);

INSERT INTO `NON_TRAINER_STAFF` VALUES (3, 'Mayank' , 'Agarwal' , NULL , 'Dusting' , 10000 , 2003);

INSERT INTO `NON_TRAINER_STAFF` VALUES (4, 'Hardik' , NULL , NULL , 'PEON' , 3000 , 2004);





INSERT INTO `FINANCE` values (NULL, 50000, 1, 100000, 50000);
INSERT INTO `FINANCE` values (NULL, 100000, 1, 200000, 100000);
INSERT INTO `FINANCE` values (NULL, 200000, 1, 300000, 100000);
INSERT INTO `FINANCE` values (NULL, 250000, 2, 400000, 150000);
INSERT INTO `FINANCE` values (NULL, 300000, 2, 500000, 200000);




INSERT INTO `EQUIPMENTS` VALUES ('Treadmill', '2001', 1, 'Good', 3, 'Legs');
INSERT INTO `EQUIPMENTS` VALUES ('Cycles', '2001', 2, 'Average', 4, 'Legs');
INSERT INTO `EQUIPMENTS` VALUES ('Bench press', '2002', 3, 'Good', 4, 'Chest');
INSERT INTO `EQUIPMENTS` VALUES ('Smith Machine', '2002', 4, 'Poor', 2, 'Shoulder');
INSERT INTO `EQUIPMENTS` VALUES ('Treadmill', '2003', 5, 'New', 2, 'Legs');
INSERT INTO `EQUIPMENTS` VALUES ('Leg Press Machine', '2003', 6, 'Good', 4, 'Legs');
INSERT INTO `EQUIPMENTS` VALUES ('Dumbbell', '2004', 7, 'Good', 2, 'Biceps');
INSERT INTO `EQUIPMENTS` VALUES ('Tricep-extention', '2004', 8, 'Average', 2, 'Triceps');




INSERT INTO `ALUMNI` VALUES (NULL, 'Parv', NULL, '100m', 'State', '1st', '2020');
INSERT INTO `ALUMNI` VALUES (NULL, 'Vastav', 'Yadav', '100m', 'District', '2nd', '2010');
INSERT INTO `ALUMNI` VALUES (NULL, 'Parth', 'Sharma', '100m', 'Inter-school', '3rd', '2020');
INSERT INTO `ALUMNI` VALUES (NULL, 'Rahul', NULL, '100m', 'State', '4th', '2016');
INSERT INTO `ALUMNI` VALUES (NULL, 'Pinky', 'Kabra', '100m', 'District', NULL , '2020');
INSERT INTO `ALUMNI` VALUES (NULL, 'Jay', 'Gupta', '100m', 'National', '6th', '2008');

